name: Cross-Platform Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: x86_64-linux
          - os: ubuntu-latest  
            platform: aarch64-linux
          - os: macos-latest
            platform: x86_64-darwin
          - os: macos-latest
            platform: arm64-darwin

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cargo-cache: true
          
      - name: Install cross-compilation dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 60
          
      - name: Build gem for platform
        run: |
          bundle install
          bundle exec rake native:micro_mcp:${{ matrix.platform }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
          path: pkg/*-${{ matrix.platform }}.gem
