name: Cross-Platform Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: x86_64-linux
            target: x86_64-linux
          - os: macos-13
            platform: x86_64-darwin
            target: x86_64-darwin22
          - os: macos-latest
            platform: arm64-darwin
            target: arm64-darwin23

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cargo-cache: true
          
      - name: Build gem for platform
        run: |
          bundle install
          bundle exec rake --tasks
          # Use native compilation for all platforms
          bundle exec rake build
          # List created files for debugging
          echo "Files in pkg directory:"
          ls -la pkg/ || echo "No pkg directory found"

      - name: Rename gem with platform suffix
        run: |
          # Find the created gem and rename it to include platform suffix
          if [ -f pkg/micro_mcp-*.gem ]; then
            for gem in pkg/micro_mcp-*.gem; do
              # Extract version from existing gem name
              version=$(echo "$gem" | sed 's/.*micro_mcp-\(.*\)\.gem/\1/')
              # Create new name with platform suffix
              new_name="pkg/micro_mcp-${version}-${{ matrix.platform }}.gem"
              mv "$gem" "$new_name"
              echo "Renamed $gem to $new_name"
              ls -la pkg/
            done
          else
            echo "No gem files found to rename"
            ls -la pkg/
          fi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gem-${{ matrix.platform }}
          path: pkg/*-${{ matrix.platform }}.gem
